### ISSUE TITLE
Support app re-sign

### ISSUE THREAD

**Issue by pablog178** [propelics/upload-apperian#1]
After a new version uploads, a new option `--sign <description>` could be added so the script will re-sign the app using the given signing credential from the list of credentials saved.

https://apidocs.apperian.com/production/signing.html#put--v1-applications-(app_psk)-credentials-(credentials_psk)

`app_psk` seems to be retrieve after the version is published, and `credentials_psk` could be retrieve from the [list of credentials](https://apidocs.apperian.com/production/signing.html#get--v1-credentials-) , based on the description.

**Comment by carlos-enciso** [comment]
PR #2
